/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package programmers.travelroute;

import java.util.Arrays;

public class App {
    public static void main(String[] args) {
        Solution s = new Solution();

        String[][] tickets =
            // {{}};
            // {{"ICN", "JFK"}, {"HND", "IAD"}, {"JFK", "HND"}, {"ICN", "JFK"}, {"IAD","ICN"}};
            // {{"ICN", "SFO"}, {"ICN", "ATL"}, {"SFO", "ATL"}, {"ICN", "ATL"}, {"ATL","ABC"}, {"ABC","ATL"},{"ATL", "ICN"}, {"ATL", "ICN"}, {"ATL","SFO"},{"SFO","ATL"}, {"ATL","ABC"}};
            // {{"ICN", "SFO"}, {"ICN", "ATL"}, {"SFO", "ATL"}, {"ATL", "ICN"}, {"ATL","SFO"}};
            {{"BBB","ICN"},{"ICN","CCC"},{"ICN","BBB"},{"CCC","BBB"}};
            // {{"ICN", "ICN"}};
        System.out.println(Arrays.asList(s.solution(tickets)));

    }
}
